name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ci:
    name: Unit Tests and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
        working-directory: lib
      - run: npm run test
        working-directory: lib
      - run: npm run build
        working-directory: lib
      - uses: actions/upload-artifact@v2
        with:
          name: dialog-player-js
          path: lib/dist
          if-no-files-found: error
